language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: Q8kbePK3x5q9pxxSD8wPTIrrcysN/vYFQgt6sCO5ccXELTl1B52QdUX3/rpLnUkRcDWT3SDrrwIb49MkeCU+4/YpG1qyIg61yf7mbU5r/Qgj01if1Dgix//fyqJ6Vlj8O2aY0zniTfhPpPu+SNRyySBYB5l7OKitHW3K5TuPRlpA4cEqrw4fX2Lp//Gnh1S4zyaMkW93EuWgohAl8kBg+FJBofbH1Zh8/AfcBDsvC0HYeGKDrX42cyT6lxbWsUBg8q1YtCbyvds0VWYjkKM8NEhU/oOHHB+ExfgQe9ug8KCrGgIA6mkX5w+44DwBgKnGLXTY1HEfdCE/bIDuxcSDREWPessL5IklbDhQYtP1YpXbH8V2bOOd7uvLkklipVnldMNdCjlf986u2FjaxE60Dmgc5QU6TxmVntJMmla+FhsWaBpDMK/R91fcj45Fh9D66UJWuYEIUxcbgNRvKYS4gnB3zRerPXDlNW3YQFwgHKCK5fLEVBo/3vme6zrU4dh1zoClA0aIPyp7rrFv4Jf52gviz7wdA9W/k1VC0ckjQYxO+fYesnUbD4mqn4z40sAejIJMxANd0PITBmsZwB61bZLqVrcPjRExEyzHJZfvu62D2QJphk/iVyk8vTfDGZqQ2UxokyhH0KK6j0KoFcMfh3qNAQjUrieFCamn4KWeOjw=
node_js:
- '6'
branches:
  only:
  - master
install:
- npm install
before_script:
- npm prune
- npm run build
script:
- if [ "$TRAVIS_EVENT_TYPE" = "pull_request" ]; then npm run test; fi
after_success:
- if [ "$TRAVIS_EVENT_TYPE" = "push" ]; then npm run release; fi
